print("Welcome to Pre-Engging")
print("\n\nสวัสดี กรอกข้อมูลตนเองครับ")
stu_number = input ("เลขที่")
nickname = input("ชื่อเล่น")
print("\n\nยินดีต้อนรับ", nickname)
print("เลขที่", stu_number)
print("\n\โชคดีครับ")